(in-package #:0xcacti-website.components)

(defmacro go-ascii () 
  `(with-html-output (*standard-output*)
      (:pre :class "text-sky-300"
       "      ´.-::::::-.´" (:br)
       "  .:-::::::::::::::-:." (:br)
       "  ´_::" (:span :class "text-gray-500" ":    ::    :") "::_´" (:br)
       "   .:" (:span :class "text-gray-500" "( ^   :: ^   )") ":." (:br)
       "   ´::" (:span :class "text-gray-500" ":   ") (:span :class "text-orange-200" "(") (:span :class "text-black" "..") (:span :class "text-orange-200" ")") (:span :class "text-gray-500" "   :") "::." (:br)
       "   ´:::::::" (:span :class "text-gray-500" "UU") ":::::::´" (:br)
       "   .::::::::::::::::." (:br)
       (:span :class "text-orange-200" "   O") "::::::::::::::::" (:span :class "text-orange-200" "O") (:br)
       "   -::::::::::::::::-" (:br)
       "   ´::::::::::::::::´" (:br)
       "    .::::::::::::::." (:br)
       (:span :class "text-orange-200" "      oO") ":::::::" (:span :class "text-orange-200" "Oo"))
  ))

(defmacro rust-ascii ()
  `(with-html-output (*standard-output*)
     (:pre :class "text-red-500"
"                 R RR RR"(:br)
"              RRRRRRRRRR R"(:br)
"            R RRRRRRRRRRRRRRR"(:br)
"            RRRRRRRRRRRRRRRRR       R"(:br)
" R RR    RRRRRRRRRRRRRRRRRRRRRR    RR"(:br)
"rR RRR    RRRRRRRRRRRRRRRRRRRRR   RRR R"(:br)
"RRR RR  RRRRRRRRRRRRRRRRRRRRRRRRR RRRRR"(:br)
" RRRRR  RRRRRRRRRRRRRRRRRRRRRRRR  RRRR"(:br)
"  RRR RRRRRRRRRRRRRRRRRRRRRRRRRRRR RR"(:br)
"    R  RRRRRRRRRR{1}=  {0}RR{1} = {0}RRRRRRRRRRR"(:br)
"     RRRRRRRRRRRr{1}=  {0}RR{1} = {0}RRRRRRRRRR"(:br)
"      RRRRRRRRRRR   RR   RRRRRRRRRR"(:br)
"     RR==RRRRRRRRRRRRRRRRRRRRRR===RR"(:br)
"     RR = .==RRRRRRR  RRRRRR==  = Rr"(:br)
"      RR =     ===========     = RR"(:br)
"       RR                        R"(:br)
"        R                       R"(:br)
"         R"(:br))))

(defmacro language (&key thoughts)
  `(with-html-output (*standard-output*)
     (:div :class "flex flex-col items-center justify-center w-full"
      ,(rust-ascii)
      (:div :class "pt-6" ,thoughts))))


